image: node:22.3.0

stages:
    - libs
    - lint
    - build

npm:
    stage: libs
    only:
        - master
    cache:
        paths:
            - node_modules
    script:
        - npm cache verify
        - npm cache clean --force
        - rm -rf package-lock.json
        - npm install --legacy-peer-deps

lint:
    stage: lint
    only:
        - master
    script:
        - npm run lint

build:
    stage: build
    only:
        - master
    cache:
        paths:
            - dist
    script:
        - npm run build
    tags:
        - akron-client