import { IRibbonTab } from 'store/ribbon-menu/RibbonMenuComponentInfo';
/**
 * ToolPane Insert Tab Data
 */
const ToolPaneInsertTabData: IRibbonTab = {
  label: '삽입',
  id: 'TOOLPANE_TAB_INSERT',
  type: 'Normal',
  groups: [
    {
      id: 'RIB_INSERT_GROUP_COMPONENT',
      label: '컴포넌트',
      type: 'Group',
      image: 'IC_RIB_COMPONENT_BASIC',
      childList: [
        {
          id: 'RIB_VARIOUS_COMPONENT_GALLERY',
          label: '컴포넌트 갤러리',
          type: 'CollapsibleGallery',
          image: 'IMG_GX_COMPONENT_DUMMY',
          tooltip: 'MSG_CM_RIBBON_TOOLTIP_TEMP',
          childList: [
            // INPUTS
            {
              id: 'RIB_INSERT_COMPONENT_MUI_INPUTS_DROPDOWN',
              label: 'Inputs',
              type: 'DropdownButton',
              image: 'IMG_GX_COMPONENT_DUMMY',
              tooltip: 'MSG_CM_RIBBON_TOOLTIP_TEMP',
              childList: [
                // {
                //   id: 'RIB_INSERT_COMPONENT_BASIC_AUTOCOMPLETE',
                //   label: 'AutoComplete',
                //   type: 'NormalButton',
                //   commandType: 'InsertWidget',
                //   commandPropName: 'BasicAutoComplete',
                //   image: 'IMG_COMPONENT_INPUT_AUTOCOMPLETE',
                // },
                {
                  id: 'RIB_INSERT_COMPONENT_BASIC_BUTTON',
                  label: 'Button',
                  type: 'NormalButton',
                  commandType: 'InsertWidget',
                  commandPropName: 'BasicButton',
                  image: 'IMG_COMPONENT_INPUT_BUTTON',
                },
                {
                  id: 'RIB_INSERT_COMPONENT_BASIC_ICON_BUTTON',
                  label: 'IconButton',
                  type: 'NormalButton',
                  commandType: 'InsertWidget',
                  commandPropName: 'BasicIconButton',
                  image: 'IMG_COMPONENT_INPUT_ICONBUTTON',
                },
                {
                  id: 'RIB_INSERT_COMPONENT_BASIC_LOADING_BUTTON',
                  label: 'LoadingButton',
                  type: 'NormalButton',
                  commandType: 'InsertWidget',
                  commandPropName: 'BasicLoadingButton',
                  image: 'IMG_COMPONENT_INPUT_LOADINGBUTTON',
                },
                {
                  id: 'RIB_INSERT_COMPONENT_BASIC_BUTTON_GROUP',
                  label: 'ButtonGroup',
                  type: 'NormalButton',
                  commandType: 'InsertWidget',
                  commandPropName: 'BasicButtonGroup',
                  image: 'IMG_COMPONENT_INPUT_BUTTONGROUP',
                },
                {
                  id: 'RIB_INSERT_COMPONENT_BASIC_CHECKBOX',
                  label: 'Checkbox',
                  type: 'NormalButton',
                  commandType: 'InsertWidget',
                  commandPropName: 'BasicCheckbox',
                  image: 'IMG_COMPONENT_INPUT_CHECKBOX',
                },
                // {
                //   id: 'RIB_INSERT_COMPONENT_BASIC_FLOATING_ACTION_BUTTON',
                //   label: 'FloatingActionButton',
                //   type: 'NormalButton',
                //   commandType: 'InsertWidget',
                //   commandPropName: 'BasicFloatingActionButton',
                //   image: 'IMG_COMPONENT_INPUT_FLOATINGACTIONBUTTON',
                // },
                {
                  id: 'RIB_INSERT_COMPONENT_BASIC_RADIO',
                  label: 'Radio',
                  type: 'NormalButton',
                  commandType: 'InsertWidget',
                  commandPropName: 'BasicRadio',
                  image: 'IMG_COMPONENT_INPUT_RADIO',
                },
                // {
                //   id: 'RIB_INSERT_COMPONENT_BASIC_RADIO_GROUP',
                //   label: 'RadioGroup',
                //   type: 'NormalButton',
                //   commandType: 'InsertWidget',
                //   commandPropName: 'BasicRadioGroup',
                //   image: 'IMG_COMPONENT_INPUT_RADIOGROUP',
                // },
                {
                  id: 'RIB_INSERT_COMPONENT_BASIC_RATING',
                  label: 'Rating',
                  type: 'NormalButton',
                  commandType: 'InsertWidget',
                  commandPropName: 'BasicRating',
                  image: 'IMG_COMPONENT_INPUT_RATING',
                },
                // {
                //   id: 'RIB_INSERT_COMPONENT_BASIC_NATIVESELECT',
                //   label: 'NativeSelect',
                //   type: 'NormalButton',
                //   commandType: 'InsertWidget',
                //   commandPropName: 'BasicNativeSelect',
                //   image: 'IMG_COMPONENT_INPUT_NATIVESELECT',
                // },
                {
                  id: 'RIB_INSERT_COMPONENT_BASIC_SELECT',
                  label: 'Select',
                  type: 'NormalButton',
                  commandType: 'InsertWidget',
                  commandPropName: 'BasicSelect',
                  image: 'IMG_COMPONENT_INPUT_SELECT',
                },
                {
                  id: 'RIB_INSERT_COMPONENT_BASIC_SLIDER',
                  label: 'Slider',
                  type: 'NormalButton',
                  commandType: 'InsertWidget',
                  commandPropName: 'BasicSlider',
                  image: 'IMG_COMPONENT_INPUT_SLIDER',
                },
                {
                  id: 'RIB_INSERT_COMPONENT_BASIC_SWITCH',
                  label: 'Switch',
                  type: 'NormalButton',
                  commandType: 'InsertWidget',
                  commandPropName: 'BasicSwitch',
                  image: 'IMG_COMPONENT_INPUT_SWITCH',
                },
                {
                  id: 'RIB_INSERT_COMPONENT_BASIC_TEXTFIELD',
                  label: 'Textfield',
                  type: 'NormalButton',
                  commandType: 'InsertWidget',
                  commandPropName: 'BasicTextField',
                  image: 'IMG_COMPONENT_INPUT_TEXTFIELD',
                },
                {
                  id: 'RIB_INSERT_COMPONENT_BASIC_TOGGLEBUTTON',
                  label: 'ToggleButton',
                  type: 'NormalButton',
                  commandType: 'InsertWidget',
                  commandPropName: 'BasicToggleButton',
                  image: 'IMG_COMPONENT_INPUT_TOGGLE',
                },
                // {
                //   id: 'RIB_INSERT_COMPONENT_BASIC_TOGGLEBUTTONGROUP',
                //   label: 'ToggleButtonGroup',
                //   type: 'NormalButton',
                //   commandType: 'InsertWidget',
                //   commandPropName: 'BasicToggleButtonGroup',
                //   image: 'IMG_COMPONENT_INPUT_TOGGLEGROUP',
                // },
              ],
            },
            // DATA DISPLAY
            {
              id: 'RIB_INSERT_COMPONENT_MUI_DATA_DISPLAY_DROPDOWN',
              label: 'Data Display',
              type: 'DropdownButton',
              image: 'IMG_GX_COMPONENT_DUMMY',
              tooltip: 'MSG_CM_RIBBON_TOOLTIP_TEMP',
              childList: [
                // DATA DISPLAY
                {
                  id: 'RIB_INSERT_COMPONENT_BASIC_AVATAR',
                  label: 'Avatar',
                  type: 'NormalButton',
                  commandType: 'InsertWidget',
                  commandPropName: 'BasicAvatar',
                  image: 'IMG_COMPONENT_DATADISPLAY_AVATAR',
                },
                // {
                //   id: 'RIB_INSERT_COMPONENT_BASIC_AVATAR_GROUP',
                //   label: 'AvatarGroup',
                //   type: 'NormalButton',
                //   commandType: 'InsertWidget',
                //   commandPropName: 'BasicAvatarGroup',
                //   image: 'IMG_COMPONENT_DATADISPLAY_AVATARGROUP',
                // },
                // {
                //   id: 'RIB_INSERT_COMPONENT_BASIC_BADGE',
                //   label: 'Badge',
                //   type: 'NormalButton',
                //   commandType: 'InsertWidget',
                //   commandPropName: 'BasicBadge',
                //   image: 'IMG_COMPONENT_DATADISPLAY_BADGE',
                // },
                // {
                //   id: 'RIB_INSERT_COMPONENT_BASIC_CHIP',
                //   label: 'Chip',
                //   type: 'NormalButton',
                //   commandType: 'InsertWidget',
                //   commandPropName: 'BasicChip',
                //   image: 'IMG_COMPONENT_DATADISPLAY_CHIP',
                // },
                {
                  id: 'RIB_INSERT_COMPONENT_BASIC_DIVIDER',
                  label: 'Divider',
                  type: 'NormalButton',
                  commandType: 'InsertWidget',
                  commandPropName: 'BasicDivider',
                  image: 'IMG_COMPONENT_DATADISPLAY_DIVIDER',
                },
                // {
                //   id: 'RIB_INSERT_COMPONENT_BASIC_LIST',
                //   label: 'List',
                //   type: 'NormalButton',
                //   commandType: 'InsertWidget',
                //   commandPropName: 'BasicList',
                //   image: 'IMG_COMPONENT_DATADISPLAY_LIST',
                // },
                // {
                //   id: 'RIB_INSERT_COMPONENT_BASIC_LISTITEM',
                //   label: 'ListItem',
                //   type: 'NormalButton',
                //   commandType: 'InsertWidget',
                //   commandPropName: 'BasicListItem',
                //   image: 'IMG_COMPONENT_LISTITEM',
                // },
                // {
                //   id: 'RIB_INSERT_COMPONENT_BASIC_LISTITEMAVATAR',
                //   label: 'ListItemAvatar',
                //   type: 'NormalButton',
                //   commandType: 'InsertWidget',
                //   commandPropName: 'BasicListItemAvatar',
                //   image: 'IMG_COMPONENT_LISTITEMAVATAR',
                // },
                // {
                //   id: 'RIB_INSERT_COMPONENT_BASIC_LISTITEMBUTTON',
                //   label: 'ListItemButton',
                //   type: 'NormalButton',
                //   commandType: 'InsertWidget',
                //   commandPropName: 'BasicListItemButton',
                //   image: 'IMG_COMPONENT_LISTITEMBUTTON',
                // },
                // {
                //   id: 'RIB_INSERT_COMPONENT_BASIC_LISTITEMICON',
                //   label: 'ListItemIcon',
                //   type: 'NormalButton',
                //   commandType: 'InsertWidget',
                //   commandPropName: 'BasicListItemIcon',
                //   image: 'IMG_COMPONENT_LISTITEMICON',
                // },
                // {
                //   id: 'RIB_INSERT_COMPONENT_BASIC_LISTITEMSECONDARYACTION',
                //   label: 'ListItemSecondaryAction',
                //   type: 'NormalButton',
                //   commandType: 'InsertWidget',
                //   commandPropName: 'BasicListItemSecondaryAction',
                //   image: 'IMG_COMPONENT_LISTITEMSECONDARYACTION',
                // },
                // {
                //   id: 'RIB_INSERT_COMPONENT_BASIC_LISTITEMTEXT',
                //   label: 'ListItemText',
                //   type: 'NormalButton',
                //   commandType: 'InsertWidget',
                //   commandPropName: 'BasicListItemText',
                //   image: 'IMG_COMPONENT_LISTITEMTEXT',
                // },
                // {
                //   id: 'RIB_INSERT_COMPONENT_BASIC_LISTSUBHEADER',
                //   label: 'ListSubheader',
                //   type: 'NormalButton',
                //   commandType: 'InsertWidget',
                //   commandPropName: 'BasicListSubheader',
                //   image: 'IMG_COMPONENT_LISTSUBHEADER',
                // },
                {
                  id: 'RIB_INSERT_COMPONENT_BASIC_TABLE',
                  label: 'Table',
                  type: 'NormalButton',
                  commandType: 'InsertWidget',
                  commandPropName: 'BasicTable',
                  image: 'IMG_COMPONENT_TABLE',
                },
                // {
                //   id: 'RIB_INSERT_COMPONENT_BASIC_TABLEBODY',
                //   label: 'TableBody',
                //   type: 'NormalButton',
                //   commandType: 'InsertWidget',
                //   commandPropName: 'BasicTableBody',
                //   image: 'IMG_COMPONENT_TABLEBODY',
                // },
                // {
                //   id: 'RIB_INSERT_COMPONENT_BASIC_TABLECELL',
                //   label: 'TableCell',
                //   type: 'NormalButton',
                //   commandType: 'InsertWidget',
                //   commandPropName: 'BasicTableCell',
                //   image: 'IMG_COMPONENT_TABLECELL',
                // },
                // {
                //   id: 'RIB_INSERT_COMPONENT_BASIC_TABLECONTAINER',
                //   label: 'TableContainer',
                //   type: 'NormalButton',
                //   commandType: 'InsertWidget',
                //   commandPropName: 'BasicTableContainer',
                //   image: 'IMG_COMPONENT_DATADISPLAY_TABLECONTAINER',
                // },
                // {
                //   id: 'RIB_INSERT_COMPONENT_BASIC_TABLEFOOTER',
                //   label: 'TableFooter',
                //   type: 'NormalButton',
                //   commandType: 'InsertWidget',
                //   commandPropName: 'BasicTableFooter',
                //   image: 'IMG_COMPONENT_TABLEFOOTER',
                // },
                // {
                //   id: 'RIB_INSERT_COMPONENT_BASIC_TABLEHEAD',
                //   label: 'TableHead',
                //   type: 'NormalButton',
                //   commandType: 'InsertWidget',
                //   commandPropName: 'BasicTableHead',
                //   image: 'IMG_COMPONENT_TABLEHEAD',
                // },
                // {
                //   id: 'RIB_INSERT_COMPONENT_BASIC_TABLEPAGINATION',
                //   label: 'TablePagination',
                //   type: 'NormalButton',
                //   commandType: 'InsertWidget',
                //   commandPropName: 'BasicTablePagination',
                //   image: 'IMG_COMPONENT_DATADISPLAY_TABLEPAGENATION',
                // },
                // {
                //   id: 'RIB_INSERT_COMPONENT_BASIC_TABLEROW',
                //   label: 'TableRow',
                //   type: 'NormalButton',
                //   commandType: 'InsertWidget',
                //   commandPropName: 'BasicTableRow',
                //   image: 'IMG_COMPONENT_TABLEROW',
                // },
                // {
                //   id: 'RIB_INSERT_COMPONENT_BASIC_TABLESORTLABEL',
                //   label: 'TableSortLabel',
                //   type: 'NormalButton',
                //   commandType: 'InsertWidget',
                //   commandPropName: 'BasicTableSortLabel',
                //   image: 'IMG_COMPONENT_TABLESORTLABEL',
                // },
                // {
                //     id: 'RIB_INSERT_COMPONENT_BASIC_TOOLTIP',
                //     label: 'Tooltip',
                //     type: 'NormalButton',
                //     commandType: 'InsertWidget',
                //     commandPropName: 'BasicTooltip',
                //     image: 'IMG_GX_COMPONENT_DUMMY',
                // },
                {
                  id: 'RIB_INSERT_COMPONENT_BASIC_TYPOGRAPHY',
                  label: 'Typography',
                  type: 'NormalButton',
                  commandType: 'InsertWidget',
                  commandPropName: 'BasicTypography',
                  image: 'IMG_COMPONENT_DATADISPLAY_TYPOGRAPHY',
                },
                {
                  id: 'RIB_INSERT_COMPONENT_BASIC_LABEL',
                  label: 'Label',
                  type: 'NormalMenuItem',
                  commandType: 'InsertWidget',
                  commandPropName: 'BasicLabel',
                  image: 'IC_COMPONENT_LABEL',
                  tooltip: 'MSG_CM_RIBBON_TOOLTIP_TEMP',
                },
              ],
            },
            // MEDIA
            {
              id: 'RIB_INSERT_COMPONENT_MUI_MEDIA_DROPDOWN',
              label: 'Media',
              type: 'DropdownButton',
              image: 'IMG_GX_COMPONENT_DUMMY',
              tooltip: 'MSG_CM_RIBBON_TOOLTIP_TEMP',
              childList: [
                // MEDIA
                {
                  id: 'RIB_INSERT_COMPONENT_BASIC_IMAGE',
                  label: 'Image',
                  type: 'NormalButton',
                  commandType: 'InsertWidget',
                  commandPropName: 'BasicImage',
                  image: 'IMG_COMPONENT_MEDIA_IMAGE',
                },
                {
                  id: 'RIB_INSERT_COMPONENT_BASIC_VIDEO',
                  label: 'Video',
                  type: 'NormalButton',
                  commandType: 'InsertWidget',
                  commandPropName: 'BasicVideo',
                  image: 'IMG_COMPONENT_MEDIA_VIDEO',
                },
              ],
            },
            // FEEDBACK
            {
              id: 'RIB_INSERT_COMPONENT_MUI_FEEDBACK_DROPDOWN',
              label: 'Feedback',
              type: 'DropdownButton',
              image: 'IMG_GX_COMPONENT_DUMMY',
              tooltip: 'MSG_CM_RIBBON_TOOLTIP_TEMP',
              childList: [
                // FEEDBACK
                {
                  id: 'RIB_INSERT_COMPONENT_BASIC_ALERT',
                  label: 'Alert',
                  type: 'NormalButton',
                  commandType: 'InsertWidget',
                  commandPropName: 'BasicAlert',
                  image: 'IMG_COMPONENT_FEEDBACK_ALERT',
                },
                // {
                //   id: 'RIB_INSERT_COMPONENT_BASIC_ALERT_TITLE',
                //   label: 'AlertTitle',
                //   type: 'NormalButton',
                //   commandType: 'InsertWidget',
                //   commandPropName: 'BasicAlertTitle',
                //   image: 'IMG_COMPONENT_ALERTTITLE',
                // },
                // {
                //   id: 'RIB_INSERT_COMPONENT_BASIC_BACKDROP',
                //   label: 'Backdrop',
                //   type: 'NormalButton',
                //   commandType: 'InsertWidget',
                //   commandPropName: 'BasicBackdrop',
                //   image: 'IMG_COMPONENT_FEEDBACK_BACKDROP',
                // },
                // {
                //   id: 'RIB_INSERT_COMPONENT_BASIC_DIALOG_ACTIONS',
                //   label: 'DialogActions',
                //   type: 'NormalButton',
                //   commandType: 'InsertWidget',
                //   commandPropName: 'BasicDialogActions',
                //   image: 'IMG_COMPONENT_DIALOGACTIONS',
                // },
                // {
                //   id: 'RIB_INSERT_COMPONENT_BASIC_DIALOG_CONTENT',
                //   label: 'DialogContent',
                //   type: 'NormalButton',
                //   commandType: 'InsertWidget',
                //   commandPropName: 'BasicDialogContent',
                //   image: 'IMG_COMPONENT_DIALOGCONTENT',
                // },
                // {
                //   id: 'RIB_INSERT_COMPONENT_BASIC_DIALOG_CONTENT_TEXT',
                //   label: 'DialogContentText',
                //   type: 'NormalButton',
                //   commandType: 'InsertWidget',
                //   commandPropName: 'BasicDialogContentText',
                //   image: 'IMG_COMPONENT_DIALOGCONTENTTEXT',
                // },
                // {
                //   id: 'RIB_INSERT_COMPONENT_BASIC_DIALOG_TITLE',
                //   label: 'DialogTitle',
                //   type: 'NormalButton',
                //   commandType: 'InsertWidget',
                //   commandPropName: 'BasicDialogTitle',
                //   image: 'IMG_COMPONENT_DIALOGTITLE',
                // },
                // {
                //   id: 'RIB_INSERT_COMPONENT_BASIC_CIRCULARPROGRESS',
                //   label: 'CircularProgress',
                //   type: 'NormalButton',
                //   commandType: 'InsertWidget',
                //   commandPropName: 'BasicCircularProgress',
                //   image: 'IMG_COMPONENT_INPUT_LOADINGBUTTON',
                // },
                // {
                //   id: 'RIB_INSERT_COMPONENT_BASIC_SKELETON',
                //   label: 'Skeleton',
                //   type: 'NormalButton',
                //   commandType: 'InsertWidget',
                //   commandPropName: 'BasicSkeleton',
                //   image: 'IMG_COMPONENT_FEEDBACK_SKELETON',
                // },
                {
                  id: 'RIB_INSERT_COMPONENT_BASIC_SNACKBAR',
                  label: 'Snackbar',
                  type: 'NormalButton',
                  commandType: 'InsertWidget',
                  commandPropName: 'BasicSnackbar',
                  image: 'IMG_COMPONENT_FEEDBACK_SNACKBAR',
                },
                // {
                //   id: 'RIB_INSERT_COMPONENT_BASIC_SNACKBARCONTENT',
                //   label: 'SnackbarContent',
                //   type: 'NormalButton',
                //   commandType: 'InsertWidget',
                //   commandPropName: 'BasicSnackbarContent',
                //   image: 'IMG_COMPONENT_FEEDBACK_SNACKBARCONTENTS',
                // },
              ],
            },
            // SURFACES
            {
              id: 'RIB_INSERT_COMPONENT_MUI_SURFACES_DROPDOWN',
              label: 'Surfaces',
              type: 'DropdownButton',
              image: 'IMG_GX_COMPONENT_DUMMY',
              tooltip: 'MSG_CM_RIBBON_TOOLTIP_TEMP',
              childList: [
                {
                  id: 'RIB_INSERT_COMPONENT_BASIC_ACCORDION',
                  label: 'Accordion',
                  type: 'NormalButton',
                  commandType: 'InsertWidget',
                  commandPropName: 'BasicAccordion',
                  image: 'IMG_COMPONENT_SURFACE_ACCORDIAN',
                },
                // {
                //   id: 'RIB_INSERT_COMPONENT_BASIC_ACCORDIONACTIONS',
                //   label: 'AccordionActions',
                //   type: 'NormalButton',
                //   commandType: 'InsertWidget',
                //   commandPropName: 'BasicAccordionActions',
                //   image: 'IMG_COMPONENT_ACCORDIANACTIONS',
                // },
                // {
                //   id: 'RIB_INSERT_COMPONENT_BASIC_ACCORDIONDETAILS',
                //   label: 'AccordionDetails',
                //   type: 'NormalButton',
                //   commandType: 'InsertWidget',
                //   commandPropName: 'BasicAccordionDetails',
                //   image: 'IMG_COMPONENT_ACCORDIANDETAILS',
                // },
                // {
                //   id: 'RIB_INSERT_COMPONENT_BASIC_ACCORDIONSUMMARY',
                //   label: 'AccordionSummary',
                //   type: 'NormalButton',
                //   commandType: 'InsertWidget',
                //   commandPropName: 'BasicAccordionSummary',
                //   image: 'IMG_COMPONENT_ACCORDIANSUMMARY',
                // },
                {
                  id: 'RIB_INSERT_COMPONENT_BASIC_APP_BAR',
                  label: 'AppBar',
                  type: 'NormalButton',
                  commandType: 'InsertWidget',
                  commandPropName: 'BasicAppBar',
                  image: 'IMG_COMPONENT_SURFACE_APPBAR',
                },
                // {
                //   id: 'RIB_INSERT_COMPONENT_BASIC_TOOL_BAR',
                //   label: 'ToolBar',
                //   type: 'NormalButton',
                //   commandType: 'InsertWidget',
                //   commandPropName: 'BasicToolbar',
                //   image: 'IMG_COMPONENT_SURFACE_TOOLBAR',
                // },
                {
                  id: 'RIB_INSERT_COMPONENT_BASIC_CARD',
                  label: 'Card',
                  type: 'NormalButton',
                  commandType: 'InsertWidget',
                  commandPropName: 'BasicCard',
                  image: 'IMG_COMPONENT_SURFACE_CARD',
                },
                // {
                //   id: 'RIB_INSERT_COMPONENT_BASIC_CARDACTIONAREA',
                //   label: 'CardActionArea',
                //   type: 'NormalButton',
                //   commandType: 'InsertWidget',
                //   commandPropName: 'BasicCardActionArea',
                //   image: 'IMG_COMPONENT_CARDACTIONAREA',
                // },
                // {
                //   id: 'RIB_INSERT_COMPONENT_BASIC_CARDACTIONS',
                //   label: 'CardActions',
                //   type: 'NormalButton',
                //   commandType: 'InsertWidget',
                //   commandPropName: 'BasicCardActions',
                //   image: 'IMG_COMPONENT_CARDACTIONS',
                // },
                // {
                //   id: 'RIB_INSERT_COMPONENT_BASIC_CARD_CONTENT',
                //   label: 'CardContent',
                //   type: 'NormalButton',
                //   commandType: 'InsertWidget',
                //   commandPropName: 'BasicCardContent',
                //   image: 'IMG_COMPONENT_CARDCONTENT',
                // },
                // {
                //   id: 'RIB_INSERT_COMPONENT_BASIC_CARD_HEADER',
                //   label: 'CardHeader',
                //   type: 'NormalButton',
                //   commandType: 'InsertWidget',
                //   commandPropName: 'BasicCardHeader',
                //   image: 'IMG_COMPONENT_CARDHEADER',
                // },
                // {
                //   id: 'RIB_INSERT_COMPONENT_BASIC_CARD_MEDIA',
                //   label: 'CardMedia',
                //   type: 'NormalButton',
                //   commandType: 'InsertWidget',
                //   commandPropName: 'BasicCardMedia',
                //   image: 'IMG_COMPONENT_CARDMEDIA',
                // },
                // {
                //   id: 'RIB_INSERT_COMPONENT_BASIC_PAPER',
                //   label: 'Paper',
                //   type: 'NormalButton',
                //   commandType: 'InsertWidget',
                //   commandPropName: 'BasicPaper',
                //   image: 'IMG_COMPONENT_SURFACE_PAPER',
                // },
              ],
            },
            // NAVIGATION
            {
              id: 'RIB_INSERT_COMPONENT_MUI_NAVIGATION_DROPDOWN',
              label: 'Navigation',
              type: 'DropdownButton',
              image: 'IMG_GX_COMPONENT_DUMMY',
              tooltip: 'MSG_CM_RIBBON_TOOLTIP_TEMP',
              childList: [
                {
                  id: 'RIB_INSERT_COMPONENT_BASIC_BOTTOMNAVIGATION',
                  label: 'BottomNavigation',
                  type: 'NormalButton',
                  commandType: 'InsertWidget',
                  commandPropName: 'BasicBottomNavigation',
                  image: 'IMG_COMPONENT_NAVIGATION_BOTTOMNAVIGATION',
                },
                // {
                //   id: 'RIB_INSERT_COMPONENT_BASIC_BOTTOMNAVIGATIONACTION',
                //   label: 'BottomNavigationAction',
                //   type: 'NormalButton',
                //   commandType: 'InsertWidget',
                //   commandPropName: 'BasicBottomNavigationAction',
                //   image: 'IMG_COMPONENT_BOTTOMNAVIGATIONACTION',
                // },
                // {
                //   id: 'RIB_INSERT_COMPONENT_BASIC_BREADCRUMBS',
                //   label: 'Breadcrumbs',
                //   type: 'NormalButton',
                //   commandType: 'InsertWidget',
                //   commandPropName: 'BasicBreadcrumbs',
                //   image: 'IMG_COMPONENT_NAVIGATION_BREADCRUMBS',
                // },
                {
                  id: 'RIB_INSERT_COMPONENT_BASIC_LINK',
                  label: 'Link',
                  type: 'NormalButton',
                  commandType: 'InsertWidget',
                  commandPropName: 'BasicLink',
                  image: 'IMG_COMPONENT_NAVIGATION_LINK',
                },
                // {
                //     id: 'RIB_INSERT_COMPONENT_BASIC_DRAWER',
                //     label: 'Drawer',
                //     type: 'NormalButton',
                //     commandType: 'InsertWidget',
                //     commandPropName: 'BasicDrawer',
                //     image: 'IMG_GX_COMPONENT_DUMMY',
                // },
                // {
                //     id: 'RIB_INSERT_COMPONENT_BASIC_SWIPEABLEDRAWER',
                //     label: 'SwipeableDrawer',
                //     type: 'NormalButton',
                //     commandType: 'InsertWidget',
                //     commandPropName: 'BasicSwipeableDrawer',
                // },
                // {
                //   id: 'RIB_INSERT_COMPONENT_BASIC_SPEEDDIAL',
                //   label: 'SpeedDial',
                //   type: 'NormalButton',
                //   commandType: 'InsertWidget',
                //   commandPropName: 'BasicSpeedDial',
                //   image: 'IMG_COMPONENT_NAVIGATION_SPEEDDIAL',
                // },
                // {
                //   id: 'RIB_INSERT_COMPONENT_BASIC_SPEEDDIALACTION',
                //   label: 'SpeedDialAction',
                //   type: 'NormalButton',
                //   commandType: 'InsertWidget',
                //   commandPropName: 'BasicSpeedDialAction',
                //   image: 'IMG_COMPONENT_SPEEDDIALACTION',
                // },
                // {
                //   id: 'RIB_INSERT_COMPONENT_BASIC_SPEEDDIALICON',
                //   label: 'SpeedDialIcon',
                //   type: 'NormalButton',
                //   commandType: 'InsertWidget',
                //   commandPropName: 'BasicSpeedDialIcon',
                //   image: 'IMG_COMPONENT_NAVIGATION_SPEEDDIALICON',
                // },
                // {
                //   id: 'RIB_INSERT_COMPONENT_BASIC_CLICKAWAYLISTENER',
                //   label: 'Click AwayListener',
                //   type: 'NormalButton',
                //   commandType: 'InsertWidget',
                //   commandPropName: 'BasicClickAwayListener',
                //   image: 'IMG_COMPONENT_NAVIGATION_CLICKAWAY',
                // },
                // {
                //    id: 'RIB_INSERT_COMPONENT_BASIC_MENU',
                //    label: 'Menu',
                //    type: 'NormalButton',
                //    commandType: 'InsertWidget',
                //    commandPropName: 'BasicMenu',
                //    image: 'IMG_GX_COMPONENT_DUMMY',
                // },
                // {
                //   id: 'RIB_INSERT_COMPONENT_BASIC_MENUITEM',
                //   label: 'MenuItem',
                //   type: 'NormalButton',
                //   commandType: 'InsertWidget',
                //   commandPropName: 'BasicMenuItem',
                //   image: 'IMG_COMPONENT_MENUITEM',
                // },
                // {
                //   id: 'RIB_INSERT_COMPONENT_BASIC_MENULIST',
                //   label: 'Menulist',
                //   type: 'NormalButton',
                //   commandType: 'InsertWidget',
                //   commandPropName: 'BasicMenuList',
                //   image: 'IMG_COMPONENT_NAVIGATION_MENULIST',
                // },
                // {
                //     id: 'RIB_INSERT_COMPONENT_BASIC_POPOVER',
                //     label: 'Popover',
                //     type: 'NormalButton',
                //     commandType: 'InsertWidget',
                //     commandPropName: 'BasicPopover',
                //     image: 'IMG_GX_COMPONENT_DUMMY',
                // },
                // {
                //     id: 'RIB_INSERT_COMPONENT_BASIC_POPPER',
                //     label: 'Popper',
                //     type: 'NormalButton',
                //     commandType: 'InsertWidget',
                //     commandPropName: 'BasicPopper',
                //     image: 'IMG_GX_COMPONENT_DUMMY',
                // },
                // {
                //   id: 'RIB_INSERT_COMPONENT_BASIC_PAGINATION',
                //   label: 'Pagination',
                //   type: 'NormalButton',
                //   commandType: 'InsertWidget',
                //   commandPropName: 'BasicPagination',
                //   image: 'IMG_COMPONENT_NAVIGATION_PAGINATION',
                // },
                // {
                //     id: 'RIB_INSERT_COMPONENT_BASIC_PAGINATIONITEM',
                //     label: 'PaginationItem',
                //     type: 'NormalButton',
                //     commandType: 'InsertWidget',
                //     commandPropName: 'BasicPaginationItem',
                //     image: 'IMG_COMPONENT_NAVIGATION_TABSCROLL',
                // },
                // {
                //   id: 'RIB_INSERT_COMPONENT_BASIC_MOBILESTEPPER',
                //   label: 'MobileStepper',
                //   type: 'NormalButton',
                //   commandType: 'InsertWidget',
                //   commandPropName: 'BasicMobileStepper',
                //   image: 'IMG_COMPONENT_NAVIGATION_MOBILESTEPPER',
                // },
                // {
                //   id: 'RIB_INSERT_COMPONENT_BASIC_STEP',
                //   label: 'Step',
                //   type: 'NormalButton',
                //   commandType: 'InsertWidget',
                //   commandPropName: 'BasicStep',
                //   image: 'IMG_COMPONENT_STEP',
                // },
                // {
                //   id: 'RIB_INSERT_COMPONENT_BASIC_STEPBUTTON',
                //   label: 'StepButton',
                //   type: 'NormalButton',
                //   commandType: 'InsertWidget',
                //   commandPropName: 'BasicStepButton',
                //   image: 'IMG_COMPONENT_STEPBUTTON',
                // },
                // {
                //   id: 'RIB_INSERT_COMPONENT_BASIC_STEPCONNECTOR',
                //   label: 'StepConnector',
                //   type: 'NormalButton',
                //   commandType: 'InsertWidget',
                //   commandPropName: 'BasicStepConnector',
                //   image: 'IMG_COMPONENT_STEPCONNECTOR',
                // },
                // {
                //   id: 'RIB_INSERT_COMPONENT_BASIC_STEPCONTENT',
                //   label: 'StepContent',
                //   type: 'NormalButton',
                //   commandType: 'InsertWidget',
                //   commandPropName: 'BasicStepContent',
                //   image: 'IMG_COMPONENT_STEPCONTENT',
                // },
                // {
                //   id: 'RIB_INSERT_COMPONENT_BASIC_STEPICON',
                //   label: 'StepIcon',
                //   type: 'NormalButton',
                //   commandType: 'InsertWidget',
                //   commandPropName: 'BasicStepIcon',
                //   image: 'IMG_COMPONENT_STEPICON',
                // },
                // {
                //   id: 'RIB_INSERT_COMPONENT_BASIC_STEPLABEL',
                //   label: 'StepLabel',
                //   type: 'NormalButton',
                //   commandType: 'InsertWidget',
                //   commandPropName: 'BasicStepLabel',
                //   image: 'IMG_COMPONENT_STEPLABEL',
                // },
                // {
                //   id: 'RIB_INSERT_COMPONENT_BASIC_STEPPER',
                //   label: 'Stepper',
                //   type: 'NormalButton',
                //   commandType: 'InsertWidget',
                //   commandPropName: 'BasicStepper',
                //   image: 'IMG_COMPONENT_NAVIGATION_STEPPER',
                // },
                // {
                //   id: 'RIB_INSERT_COMPONENT_BASIC_TAB',
                //   label: 'Tab',
                //   type: 'NormalButton',
                //   commandType: 'InsertWidget',
                //   commandPropName: 'BasicTab',
                //   image: 'IMG_COMPONENT_TAB',
                // },
                // {
                //   id: 'RIB_INSERT_COMPONENT_BASIC_TAB_CONTEXT',
                //   label: 'TabContext',
                //   type: 'NormalButton',
                //   commandType: 'InsertWidget',
                //   commandPropName: 'BasicTabContext',
                //   image: 'IMG_COMPONENT_TABCONTEXT',
                // },
                // {
                //     id: 'RIB_INSERT_COMPONENT_BASIC_TAB_LIST',
                //     label: 'TabList',
                //     type: 'NormalButton',
                //     commandType: 'InsertWidget',
                //     commandPropName: 'BasicTabList',
                //     image: 'IMG_GX_COMPONENT_DUMMY',
                // },
                // {
                //   id: 'RIB_INSERT_COMPONENT_BASIC_TAB_PANEL',
                //   label: 'TabPanel',
                //   type: 'NormalButton',
                //   commandType: 'InsertWidget',
                //   commandPropName: 'BasicTabPanel',
                //   image: 'IMG_COMPONENT_TABPANNEL',
                // },
                // {
                //   id: 'RIB_INSERT_COMPONENT_BASIC_TAB_SCROLL_BUTTON',
                //   label: 'Tab ScrollButton',
                //   type: 'NormalButton',
                //   commandType: 'InsertWidget',
                //   commandPropName: 'BasicTabScrollButton',
                //   image: 'IMG_COMPONENT_NAVIGATION_TABSCROLL',
                // },
                {
                  id: 'RIB_INSERT_COMPONENT_BASIC_TABS',
                  label: 'Tabs',
                  type: 'NormalButton',
                  commandType: 'InsertWidget',
                  commandPropName: 'BasicTabs',
                  image: 'IMG_COMPONENT_NAVIGATION_TAB',
                },
              ],
            },
            // LAYOUT
            {
              id: 'RIB_INSERT_COMPONENT_MUI_LAYOUT_DROPDOWN',
              label: 'Layout',
              type: 'DropdownButton',
              image: 'IMG_GX_COMPONENT_DUMMY',
              tooltip: 'MSG_CM_RIBBON_TOOLTIP_TEMP',
              childList: [
                {
                  id: 'RIB_INSERT_COMPONENT_LAYOUT_HORIZONTALFRAME',
                  label: 'Horizontal Layout',
                  type: 'NormalButton',
                  commandType: 'InsertWidget',
                  commandPropName: 'LayoutHorizontalFrame',
                  image: 'IMG_COMPONENT_HORIZONTALLAYOUT',
                },
                {
                  id: 'RIB_INSERT_COMPONENT_LAYOUT_VERTICALFRAME',
                  label: 'Vertical Layout',
                  type: 'NormalButton',
                  commandType: 'InsertWidget',
                  commandPropName: 'LayoutVerticalFrame',
                  image: 'IMG_COMPONENT_VERTICALLAYOUT',
                },
                {
                  id: 'RIB_INSERT_COMPONENT_CONDITIONAL_LAYOUT',
                  label: 'Conditional Layout',
                  type: 'NormalButton',
                  commandType: 'InsertWidget',
                  commandPropName: 'ConditionalLayout',
                  image: 'IMG_COMPONENT_CONDITIONALLAYOUT',
                },
                // {
                //   id: 'RIB_INSERT_COMPONENT_REPEATABLE_LAYOUT',
                //   label: 'Repeatable Layout',
                //   type: 'NormalButton',
                //   commandType: 'InsertWidget',
                //   commandPropName: 'RepeatableLayout',
                //   image: 'IMG_COMPONENT_REPEATABLELAYOUT',
                // },
                // {
                //   id: 'RIB_INSERT_COMPONENT_INFINITE_SCROLL',
                //   label: 'Infinite Layout',
                //   type: 'NormalButton',
                //   commandType: 'InsertWidget',
                //   commandPropName: 'InfiniteLayout',
                //   image: 'IMG_COMPONENT_INFINITELAYOUT',
                // },
                // {
                //   id: 'RIB_INSERT_COMPONENT_SCREEN_LAYOUT',
                //   label: 'Screen Layout',
                //   type: 'NormalButton',
                //   commandType: 'InsertWidget',
                //   commandPropName: 'ScreenLayout',
                //   image: 'IMG_COMPONENT_SCREENLAYOUT',
                // },
                // {
                //   id: 'RIB_INSERT_COMPONENT_INNER_PAGE_LAYOUT',
                //   label: 'Inner Page Layout',
                //   type: 'NormalButton',
                //   commandType: 'InsertWidget',
                //   commandPropName: 'InnerPageLayout',
                //   image: 'IMG_COMPONENT_INNERPAGELAYOUT',
                // },
                // {
                //   id: 'RIB_INSERT_COMPONENT_BASIC_BOX',
                //   label: 'Box',
                //   type: 'NormalButton',
                //   commandType: 'InsertWidget',
                //   commandPropName: 'BasicBox',
                //   image: 'IMG_COMPONENT_BOX',
                // },
                // {
                //   id: 'RIB_INSERT_COMPONENT_BASIC_CONTAINER',
                //   label: 'Container',
                //   type: 'NormalButton',
                //   commandType: 'InsertWidget',
                //   commandPropName: 'BasicContainer',
                //   image: 'IMG_COMPONENT_CONTAINER',
                // },
                {
                  id: 'RIB_INSERT_COMPONENT_BASIC_GRID',
                  label: 'Grid',
                  type: 'NormalButton',
                  commandType: 'InsertWidget',
                  commandPropName: 'BasicGrid',
                  image: 'IMG_COMPONENT_GRID',
                },
                {
                  id: 'RIB_INSERT_COMPONENT_BASIC_STACK',
                  label: 'Stack',
                  type: 'NormalButton',
                  commandType: 'InsertWidget',
                  commandPropName: 'BasicStack',
                  image: 'IMG_COMPONENT_STACK',
                },
                // {
                //   id: 'RIB_INSERT_COMPONENT_BASIC_IMAGELIST',
                //   label: 'Image List',
                //   type: 'NormalButton',
                //   commandType: 'InsertWidget',
                //   commandPropName: 'BasicImageList',
                //   image: 'IMG_COMPONENT_IMAGELIST',
                // },
                // {
                //   id: 'RIB_INSERT_COMPONENT_BASIC_IMAGELISTITEM',
                //   label: 'ImageListItem',
                //   type: 'NormalButton',
                //   commandType: 'InsertWidget',
                //   commandPropName: 'BasicImageListItem',
                //   image: 'IMG_COMPONENT_IMAGELISTITEM',
                // },
                // {
                //   id: 'RIB_INSERT_COMPONENT_BASIC_IMAGELISTITEMBAR',
                //   label: 'ImageListItemBar',
                //   type: 'NormalButton',
                //   commandType: 'InsertWidget',
                //   commandPropName: 'BasicImageListItemBar',
                //   image: 'IMG_COMPONENT_IMAGELISTITEMBAR',
                // },
              ],
            },
            {
              id: 'RIB_INSERT_COMPONENT_MUI_DATE_AND_TIME_PICKERS_DROPDOWN',
              label: 'Date and Time pickers',
              type: 'DropdownButton',
              image: 'IMG_GX_COMPONENT_DUMMY',
              tooltip: 'MSG_CM_RIBBON_TOOLTIP_TEMP',
              childList: [
                {
                  id: 'RIB_INSERT_COMPONENT_BASIC_CALENDAR',
                  label: 'Calendar',
                  type: 'NormalButton',
                  commandType: 'InsertWidget',
                  commandPropName: 'BasicDate',
                  image: 'IMG_COMPONENT_DATEANDTIMEPICKER_CALENDAR',
                },
                // {
                //   id: 'RIB_INSERT_COMPONENT_BASIC_CALENDARPICKER',
                //   label: 'CalendarPicker',
                //   type: 'NormalButton',
                //   commandType: 'InsertWidget',
                //   commandPropName: 'BasicCalendarPicker',
                //   image: 'IMG_COMPONENT_CALENDARPICKER',
                // },
                // {
                //   id: 'RIB_INSERT_COMPONENT_BASIC_CALENDARPICKERSKELETON',
                //   label: 'CalendarPickerSkeleton',
                //   type: 'NormalButton',
                //   commandType: 'InsertWidget',
                //   commandPropName: 'BasicCalendarPickerSkeleton',
                //   image: 'IMG_COMPONENT_DATEANDTIMEPICKER_CALENDARPICKERSKELETON',
                // },
                {
                  id: 'RIB_INSERT_COMPONENT_BASIC_COLORPICKER',
                  label: 'Color Picker',
                  type: 'NormalButton',
                  commandType: 'InsertWidget',
                  commandPropName: 'BasicColor',
                  image: 'IMG_COMPONENT_DATEANDTIMEPICKER_COLORPICKER',
                },
                // {
                //   id: 'RIB_INSERT_COMPONENT_BASIC_CLOCKPICKER',
                //   label: 'ClockPicker',
                //   type: 'NormalButton',
                //   commandType: 'InsertWidget',
                //   commandPropName: 'BasicClockPicker',
                //   image: 'IMG_COMPONENT_CLOCKPICKER',
                // },
                // {
                //   id: 'RIB_INSERT_COMPONENT_BASIC_DATEPICKER',
                //   label: 'Date Picker',
                //   type: 'NormalButton',
                //   commandType: 'InsertWidget',
                //   commandPropName: 'BasicDatePicker',
                //   image: 'IMG_COMPONENT_DATEANDTIMEPICKER_DATEPICKERCALENDAR',
                // },
                // {
                //   id: 'RIB_INSERT_COMPONENT_BASIC_DATETIMEPICKER',
                //   label: 'Date TimePicker',
                //   type: 'NormalButton',
                //   commandType: 'InsertWidget',
                //   commandPropName: 'BasicDateTimePicker',
                //   image: 'IMG_COMPONENT_DATEANDTIMEPICKER_DATETIMEPICKER',
                // },
                // {
                //   id: 'RIB_INSERT_COMPONENT_BASIC_DESKTOPDATEPICKER',
                //   label: 'DesktopDate Picker',
                //   type: 'NormalButton',
                //   commandType: 'InsertWidget',
                //   commandPropName: 'BasicDesktopDatePicker',
                //   image: 'IMG_COMPONENT_DATEANDTIMEPICKER_DESKTOPDATEPICKER',
                // },
                // {
                //   id: 'RIB_INSERT_COMPONENT_BASIC_DESKTOPDATETIMEPICKER',
                //   label: 'DesktopDateTimePicker',
                //   type: 'NormalButton',
                //   commandType: 'InsertWidget',
                //   commandPropName: 'BasicDesktopDateTimePicker',
                //   image: 'IMG_COMPONENT_DATEANDTIMEPICKER_DESKTOPDATETIMEPICKER',
                // },
                // {
                //   id: 'RIB_INSERT_COMPONENT_BASIC_DESKTOPTIMEPICKER',
                //   label: 'DesktopTime Picker',
                //   type: 'NormalButton',
                //   commandType: 'InsertWidget',
                //   commandPropName: 'BasicDesktopTimePicker',
                //   image: 'IMG_COMPONENT_DATEANDTIMEPICKER_DESKTOPTIMEPICKER',
                // },
                // {
                //   id: 'RIB_INSERT_COMPONENT_BASIC_MOBILEDATEPICKER',
                //   label: 'MobileDate Picker',
                //   type: 'NormalButton',
                //   commandType: 'InsertWidget',
                //   commandPropName: 'BasicMobileDatePicker',
                //   image: 'IMG_COMPONENT_DATEANDTIMEPICKER_MOBILEDATETIMEPICKER',
                // },
                // {
                //   id: 'RIB_INSERT_COMPONENT_BASIC_MOBILEDATETIMEPICKER',
                //   label: 'MobileDateTimePicker',
                //   type: 'NormalButton',
                //   commandType: 'InsertWidget',
                //   commandPropName: 'BasicMobileDateTimePicker',
                //   image: 'IMG_COMPONENT_DATEANDTIMEPICKER_MOBILEDATETIMEPICKER',
                // },
                // {
                //   id: 'RIB_INSERT_COMPONENT_BASIC_MOBILETIMEPICKER',
                //   label: 'MobileTime Picker',
                //   type: 'NormalButton',
                //   commandType: 'InsertWidget',
                //   commandPropName: 'BasicMobileTimePicker',
                //   image: 'IMG_COMPONENT_DATEANDTIMEPICKER_MOBILETIMEPICKER',
                // },
                // {
                //   id: 'RIB_INSERT_COMPONENT_BASIC_MONTHPICKER',
                //   label: 'MonthPicker',
                //   type: 'NormalButton',
                //   commandType: 'InsertWidget',
                //   commandPropName: 'BasicMonthPicker',
                //   image: 'IMG_COMPONENT_DATEANDTIMEPICKER_MONTHPICKER',
                // },
                // {
                //   id: 'RIB_INSERT_COMPONENT_BASIC_PICKERSDAY',
                //   label: 'Pickers Day',
                //   type: 'NormalButton',
                //   commandType: 'InsertWidget',
                //   commandPropName: 'BasicPickersDay',
                //   image: 'IMG_COMPONENT_DATEANDTIMEPICKER_PICKERSDAY',
                // },
                // {
                //   id: 'RIB_INSERT_COMPONENT_BASIC_STATICDATEPICKER',
                //   label: 'Static DatePicker',
                //   type: 'NormalButton',
                //   commandType: 'InsertWidget',
                //   commandPropName: 'BasicStaticDatePicker',
                //   image: 'IMG_COMPONENT_DATEANDTIMEPICKER_STATICDATEPICKER',
                // },
                // {
                //   id: 'RIB_INSERT_COMPONENT_BASIC_STATICDATETIMEPICKER',
                //   label: 'Static DateTime Picker',
                //   type: 'NormalButton',
                //   commandType: 'InsertWidget',
                //   commandPropName: 'BasicStaticDateTimePicker',
                //   image: 'IMG_COMPONENT_DATEANDTIMEPICKER_STATICMOBILEDATETIMEPICKER',
                // },
                // {
                //   id: 'RIB_INSERT_COMPONENT_BASIC_STATICTIMEPICKER',
                //   label: 'Static TimePicker',
                //   type: 'NormalButton',
                //   commandType: 'InsertWidget',
                //   commandPropName: 'BasicStaticTimePicker',
                //   image: 'IMG_COMPONENT_DATEANDTIMEPICKER_STATICTIMEPICKER',
                // },
                // {
                //   id: 'RIB_INSERT_COMPONENT_BASIC_TIMEPICKER',
                //   label: 'Time Picker',
                //   type: 'NormalButton',
                //   commandType: 'InsertWidget',
                //   commandPropName: 'BasicTimePicker',
                //   image: 'IMG_COMPONENT_DATEANDTIMEPICKER_TIMEPICKER',
                // },
                // {
                //   id: 'RIB_INSERT_COMPONENT_BASIC_YEARPICKER',
                //   label: 'Year Picker',
                //   type: 'NormalButton',
                //   commandType: 'InsertWidget',
                //   commandPropName: 'BasicYearPicker',
                //   image: 'IMG_COMPONENT_DATEANDTIMEPICKER_YEARPICKER',
                // },
              ],
            },

            // STUDIO

            {
              id: 'RIB_INSERT_GROUP_WIDGET',
              label: 'Widget',
              type: 'Group',
              image: 'IC_RIB_COMPONENT_MAP',
              childList: [
                {
                  id: 'RIB_INSERT_COMPONENT_MAP_GOOGLE',
                  label: '구글 지도',
                  type: 'NormalMenuItem',
                  commandType: 'InsertWidget',
                  commandPropName: 'BasicMap',
                  image: 'IC_COMPONENT_MAP',
                },
                // {
                //     id: 'RIB_INSERT_COMPONENT_IFRAME',
                //     label: '아이프레임',
                //     type: 'NormalMenuItem',
                //     commandType: 'InsertWidget',
                //     commandPropName: 'BasicIframe',
                //     image: 'IC_RIB_SET_ADD_16',
                // },
                // {
                //     id: 'RIB_INSERT_COMPONENT_PHONE',
                //     label: '전화',
                //     type: 'NormalButton',
                //     commandType: 'InsertWidget',
                //     commandPropName: 'BasicPhone',
                //     image: 'IC_RIB_COMPONENT_PHONE',
                //     tooltip: 'MSG_CM_RIBBON_TOOLTIP_TEMP',
                // },
                // {
                //     id: 'RIB_INSERT_COMPONENT_GPS',
                //     label: 'GPS',
                //     type: 'NormalButton',
                //     commandType: 'InsertWidget',
                //     commandPropName: 'BasicGPS',
                //     image: 'IC_RIB_COMPONENT_GPS',
                //     tooltip: 'MSG_CM_RIBBON_TOOLTIP_TEMP',
                // },
                // {
                //     id: 'RIB_INSERT_COMPONENT_BASIC_IMAGE_GALLERY_LOCAL',
                //     label: '갤러리',
                //     type: 'NormalButton',
                //     commandType: 'InsertWidget',
                //     commandPropName: 'BasicImageGallery',
                //     image: 'IC_RIB_COMPONENT_INSERT_IMG',
                //     tooltip: 'MSG_CM_RIBBON_TOOLTIP_TEMP',
                // },
                // {
                //   id: 'RIB_INSERT_COMPONENT_BASIC_DIVISION',
                //   label: 'Division',
                //   type: 'NormalMenuItem',
                //   commandType: 'InsertWidget',
                //   commandPropName: 'BasicDivision',
                //   image: 'IC_COMPONENT_DIVISION',
                // },
                // {
                //   id: 'RIB_INSERT_COMPONENT_BASIC_PARAGRAPH',
                //   label: 'Paragraph',
                //   type: 'NormalMenuItem',
                //   commandType: 'InsertWidget',
                //   commandPropName: 'BasicParagraph',
                //   image: 'IC_COMPONENT_PARAGRAPH',
                // },
                // {
                //   id: 'RIB_INSERT_COMPONENT_BASIC_PROGRESSBAR',
                //   label: 'ProgressBar',
                //   type: 'NormalMenuItem',
                //   commandType: 'InsertWidget',
                //   commandPropName: 'BasicLinearProgress',
                //   image: 'IC_COMPONENT_PROGRESS',
                // },
                // {
                //     id: 'RIB_INSERT_COMPONENT_BASIC_LABEL',
                //     label: '레이블',
                //     type: 'NormalMenuItem',
                //     commandType: 'InsertWidget',
                //     commandPropName: 'BasicLabel',
                //     image: 'IC_RIB_COMPONENT_LABEL',
                //     tooltip: 'MSG_CM_RIBBON_TOOLTIP_TEMP',
                // },
                // {
                //   id: 'RIB_INSERT_COMPONENT_BASIC_OPTION',
                //   label: '옵션',
                //   type: 'NormalMenuItem',
                //   commandType: 'InsertWidget',
                //   commandPropName: 'BasicOption',
                //   image: 'IC_ADD',
                // },
              ],
            },
          ],
        },
      ],
    },
    // {
    //     id: 'RIB_INSERT_GROUP_WIDGET',
    //     label: '위젯',
    //     type: 'Group',
    //     image: 'IC_RIB_COMPONENT_MAP',
    //     childList: [
    //         {
    //             id: 'RIB_INSERT_COMPONENT_MAP_GOOGLE',
    //             label: '구글 지도',
    //             type: 'NormalMenuItem',
    //             commandType: 'InsertWidget',
    //             commandPropName: 'BasicMap',
    //             image: 'IC_RIB_COMPONENT_MAP',
    //         },
    //         // {
    //         //     id: 'RIB_INSERT_COMPONENT_IFRAME',
    //         //     label: '아이프레임',
    //         //     type: 'NormalMenuItem',
    //         //     commandType: 'InsertWidget',
    //         //     commandPropName: 'BasicIframe',
    //         //     image: 'IC_RIB_SET_ADD_16',
    //         // },
    //         // {
    //         //     id: 'RIB_INSERT_COMPONENT_PHONE',
    //         //     label: '전화',
    //         //     type: 'NormalButton',
    //         //     commandType: 'InsertWidget',
    //         //     commandPropName: 'BasicPhone',
    //         //     image: 'IC_RIB_COMPONENT_PHONE',
    //         //     tooltip: 'MSG_CM_RIBBON_TOOLTIP_TEMP',
    //         // },
    //         // {
    //         //     id: 'RIB_INSERT_COMPONENT_GPS',
    //         //     label: 'GPS',
    //         //     type: 'NormalButton',
    //         //     commandType: 'InsertWidget',
    //         //     commandPropName: 'BasicGPS',
    //         //     image: 'IC_RIB_COMPONENT_GPS',
    //         //     tooltip: 'MSG_CM_RIBBON_TOOLTIP_TEMP',
    //         // },
    //         {
    //             id: 'RIB_INSERT_COMPONENT_BASIC_IMAGE_GALLERY_LOCAL',
    //             label: '갤러리',
    //             type: 'NormalButton',
    //             commandType: 'InsertWidget',
    //             commandPropName: 'BasicImageGallery',
    //             image: 'IC_RIB_COMPONENT_INSERT_IMG',
    //             tooltip: 'MSG_CM_RIBBON_TOOLTIP_TEMP',
    //         },
    //         {
    //             id: 'RIB_INSERT_COMPONENT_BASIC_DIVISION',
    //             label: 'Division',
    //             type: 'NormalMenuItem',
    //             commandType: 'InsertWidget',
    //             commandPropName: 'BasicDivision',
    //             image: 'IC_RIB_SET_ADD_16',
    //         },
    //         {
    //             id: 'RIB_INSERT_COMPONENT_BASIC_PARAGRAPH',
    //             label: 'Paragraph',
    //             type: 'NormalMenuItem',
    //             commandType: 'InsertWidget',
    //             commandPropName: 'BasicParagraph',
    //             image: 'IC_RIB_SET_ADD_16',
    //         },
    //         {
    //             id: 'RIB_INSERT_COMPONENT_BASIC_PROGRESSBAR',
    //             label: 'ProgressBar',
    //             type: 'NormalMenuItem',
    //             commandType: 'InsertWidget',
    //             commandPropName: 'BasicLinearProgress',
    //             image: 'IC_RIB_SET_ADD_16',
    //         },
    //         // {
    //         //     id: 'RIB_INSERT_COMPONENT_BASIC_LABEL',
    //         //     label: '레이블',
    //         //     type: 'NormalMenuItem',
    //         //     commandType: 'InsertWidget',
    //         //     commandPropName: 'BasicLabel',
    //         //     image: 'IC_RIB_COMPONENT_LABEL',
    //         //     tooltip: 'MSG_CM_RIBBON_TOOLTIP_TEMP',
    //         // },
    //         {
    //             id: 'RIB_INSERT_COMPONENT_BASIC_OPTION',
    //             label: '옵션',
    //             type: 'NormalMenuItem',
    //             commandType: 'InsertWidget',
    //             commandPropName: 'BasicOption',
    //             image: 'IC_RIB_SET_ADD_16',
    //         },
    //     ],
    // },
  ],
};

export default ToolPaneInsertTabData;
